# #######
# register a new hotel
POST  http://localhost:4000/hotels
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyZDZkOTBiLTRmZGMtNGQxOS1hNDIyLWFhZDFjZDQzY2M1NiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTFAZ21haWwuY29tIiwiaWF0IjoxNzE5NTM0OTA1LCJleHAiOjE3MjEyNjI5MDV9.dlI33zL2PlZQP0O5cdjxqzz1qVvTlWy25qB3X6bltbE
Content-Type: application/json

{
    "h_name": "Hôtel Martinez",
    "h_image_url": "https://cdn.pixabay.com/photo/2023/03/29/10/27/hotel-7885138_640.jpg",
    "h_description": "Step onto the glamorous French Riviera at Hôtel Martinez. This historic landmark oozes sophistication with its Art Deco flair and beachfront location.  Imagine relaxing at a luxurious spa, indulging in decadent French cuisine, and unwinding on the Mediterranean coast.  Hôtel Martinez is Cannes' epitome of luxury.",
    "h_location": "Cannes, France",
    "h_rating": 4,
    "h_price": 1000
}


#######
# get all hotels
GET http://localhost:4000/hotels


#######
# get a specific hotel
GET http://localhost:4000/hotels/9e17653a-45de-4989-8c8e-801964d21b8a
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyZDZkOTBiLTRmZGMtNGQxOS1hNDIyLWFhZDFjZDQzY2M1NiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTFAZ21haWwuY29tIiwiaWF0IjoxNzE5NTM0OTA1LCJleHAiOjE3MjEyNjI5MDV9.dlI33zL2PlZQP0O5cdjxqzz1qVvTlWy25qB3X6bltbE


#######
# update a hotel
PUT http://localhost:4000/hotels/9e17653a-45de-4989-8c8e-801964d21b8a
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyZDZkOTBiLTRmZGMtNGQxOS1hNDIyLWFhZDFjZDQzY2M1NiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTFAZ21haWwuY29tIiwiaWF0IjoxNzE5NTM0OTA1LCJleHAiOjE3MjEyNjI5MDV9.dlI33zL2PlZQP0O5cdjxqzz1qVvTlWy25qB3X6bltbE
Content-Type: application/json

{
    "h_name": "Weston hotel",
    "h_image_url": "https://cdn.pixabay.com/photo/2014/07/21/19/20/lobby-398845_640.jpg",
    "h_rating": 0,
    "h_price": 1
}


###########
# delete a hotel
DELETE http://localhost:4000/hotels/9e17653a-45de-4989-8c8e-801964d21b8a
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyZDZkOTBiLTRmZGMtNGQxOS1hNDIyLWFhZDFjZDQzY2M1NiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTFAZ21haWwuY29tIiwiaWF0IjoxNzE5NTM0OTA1LCJleHAiOjE3MjEyNjI5MDV9.dlI33zL2PlZQP0O5cdjxqzz1qVvTlWy25qB3X6bltbE

