# #######
# register a new user
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "u_name": "Sir Maguire",
    "u_email": "maguire@gmail.com",
    "u_password": "@Shinra13K)"
}


#######
# get all users
GET http://localhost:4000/auth/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5MjZlMGM1LTc0MGItNGYwZC1iOTRlLWE3ZjZmN2U4M2U1YyIsIm5hbWUiOiJTaXIgR2F3YWluIiwiZW1haWwiOiJta3VydWdlbnppQGdtYWlsLmNvbSIsImlhdCI6MTcxODYxMDYyNSwiZXhwIjoxNzE5MjE1NDI1fQ.wct_WfzhWO3-KWUgTDTBESQVhSxUqGvabrDKMT8qOvQ


#######
# get a specific user
GET http://localhost:4000/auth/faaab895-41fa-4af3-b50e-94765da678d7


#######
# update a user
PUT http://localhost:4000/auth/faaab895-41fa-4af3-b50e-94765da678d7
Content-Type: application/json

{
    "u_name": "Failure",
    "u_email": "failuremaguire@gmail.com",
    "u_password": "@Shinra13K)"
}


###########
# delete a user
DELETE http://localhost:4000/auth/faaab895-41fa-4af3-b50e-94765da678d7
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5MjZlMGM1LTc0MGItNGYwZC1iOTRlLWE3ZjZmN2U4M2U1YyIsIm5hbWUiOiJTaXIgR2F3YWluIiwiZW1haWwiOiJta3VydWdlbnppQGdtYWlsLmNvbSIsImlhdCI6MTcxODYxMDYyNSwiZXhwIjoxNzE5MjE1NDI1fQ.wct_WfzhWO3-KWUgTDTBESQVhSxUqGvabrDKMT8qOvQ

