# #######
# register a new user
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "u_name": "Blue",
    "u_email": "blue@gmail.com",
    "u_password": "@Shinra13K)"
}



# login an existing user
############
POST  http://localhost:4000/auth/login
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNmFmZjUxLTA3ZGUtNGEzNy1iYjQyLTRlZTU2MzAyYTE5ZiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTE3QGdtYWlsLmNvbSIsImlhdCI6MTcxOTY2Nzk2OSwiZXhwIjoxNzIxMzk1OTY5fQ.Ed_E8LInHO986CeDAQflpH4Dpk1aFKdpdKiAjY1DtuE
Content-Type: application/json

{
    "u_email": "blue@gmail.com",
    "u_password": "@Shinra13K)"
}


#######
# get all users
GET http://localhost:4000/auth/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNmFmZjUxLTA3ZGUtNGEzNy1iYjQyLTRlZTU2MzAyYTE5ZiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTE3QGdtYWlsLmNvbSIsImlhdCI6MTcxOTY2Nzk2OSwiZXhwIjoxNzIxMzk1OTY5fQ.Ed_E8LInHO986CeDAQflpH4Dpk1aFKdpdKiAjY1DtuE

#######
# get a specific user
GET http://localhost:4000/auth/faaab895-41fa-4af3-b50e-94765da678d7


#######
# update a user
PUT http://localhost:4000/auth/faaab895-41fa-4af3-b50e-94765da678d7
Content-Type: application/json

{
    "u_name": "Failure",
    "u_email": "failuremaguire@gmail.com",
    "u_password": "@Shinra13K)"
}


###########
# delete a user
DELETE http://localhost:4000/auth/faaab895-41fa-4af3-b50e-94765da678d7
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNmFmZjUxLTA3ZGUtNGEzNy1iYjQyLTRlZTU2MzAyYTE5ZiIsIm5hbWUiOiJTaXIgTWFndWlyZSIsImVtYWlsIjoibWFndWlyZTE3QGdtYWlsLmNvbSIsImlhdCI6MTcxOTY2Nzk2OSwiZXhwIjoxNzIxMzk1OTY5fQ.Ed_E8LInHO986CeDAQflpH4Dpk1aFKdpdKiAjY1DtuE
