# #######
# register a new hotel
POST  http://localhost:4000/hotels
Content-Type: application/json

{
    "h_name": "Kwa Charlo",
    "h_image_url": "https://cdn.pixabay.com/photo/2014/07/21/19/20/lobby-398845_640.jpg",
    "h_rating": 1,
    "h_price": 1000
}


#######
# get all hotels
GET http://localhost:4000/hotels


#######
# get a specific hotel
GET http://localhost:4000/hotels/9e17653a-45de-4989-8c8e-801964d21b8a


#######
# update a hotel
PUT http://localhost:4000/hotels/9e17653a-45de-4989-8c8e-801964d21b8a
Content-Type: application/json

{
    "h_name": "the Intercontinental ",
    "h_image_url": "https://cdn.pixabay.com/photo/2014/07/21/19/20/lobby-398845_640.jpg",
    "h_rating": 0,
    "h_price": 1
}


###########
# delete a hotel
DELETE http://localhost:4000/hotels/9e17653a-45de-4989-8c8e-801964d21b8a

