# #######
# add a new tour
POST  http://localhost:4000/tours
Content-Type: application/json

{
    "t_name": "MaasaiMara on Valentines",
    "t_image_url": "https://cdn.pixabay.com/photo/2014/04/10/15/37/snowman-321034_640.jpg",
    "t_rating": 4,
    "t_price": 120000
}


#######
# get all tours
GET http://localhost:4000/tours


#######
# get a specific tour
GET http://localhost:4000/tours/23bd47c7-97e4-413e-ae3a-b34cde17b4cd


#######
# update a tour
PUT http://localhost:4000/tours/23bd47c7-97e4-413e-ae3a-b34cde17b4cd
Content-Type: application/json

{
    "t_name": "MaasaiMara on Valentines",
    "t_image_url": "https://cdn.pixabay.com/photo/2014/04/10/15/37/snowman-321034_640.jpg",
    "t_rating": 4,
    "t_price": 120000
}


###########
# delete a tour
DELETE http://localhost:4000/tours/23bd47c7-97e4-413e-ae3a-b34cde17b4cd

