# #######
# register a new user
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "u_name": "Lady Morgana",
    "u_email": "morgana@gmail.com",
    "u_password": "@Shinra13K)"
}


#######
# get all users
GET http://localhost:4000/auth/users


#######
# get a specific user
GET http://localhost:4000/auth/3e9aade9-7560-494b-aa2f-d0fcc0447df5


# ##########
# update a user
PUT http://localhost/auth/3e9aade9-7560-494b-aa2f-d0fcc0447df5



###########
# delete a user
DELETE http://localhost:4000/auth/3e9aade9-7560-494b-aa2f-d0fcc0447df5

