GET http://localhost:4000/products



########
POST http://localhost:4000/products
Content-Type: application/json

{
    "title": "Jordan 7s",
    "description": "looku ni mbwakni",
    "price": 124
}


#####
GET http://localhost:4000/products/4083


#####
PUT http://localhost:4000/products/2768
Content-Type: application/json

{
    "title": "we wacha",
    "description": "mkuu",
    "price": 124
}


#####
DELETE  http://localhost:4000/products/4447


#########