#####
# add a product
POST  http://localhost:4000/products
Content-Type: application/json

{
    "name":"kitunguu",
    "price":10
}



######
# get all the products
GET http://localhost:4000/products


######
# get a single product 
GET http://localhost:4000/products/05d3468b-ed39-465f-a1f8-ca88c7f334f0


##########
# update a product
PUT http://localhost:4000/products/05d3468b-ed39-465f-a1f8-ca88c7f334f0
Content-Type: application/json

{
    "name":"mandizi",
    "price":10000
}


#########
# delete a product
DELETE http://localhost:4000/products/05d3468b-ed39-465f-a1f8-ca88c7f334f0

