#####
# add a product
POST  http://localhost:4000/products
Content-Type: application/json

{
    "name":"ngombe",
    "price":4000
}



#######
# get all the products
GET http://localhost:4000/products




#######
#search
GET http://localhost:4000/products/search
Content-Type: application/json

{
    "name" : "kitunguu"
}


#######
# pagination
GET http://localhost:4000/products/filter
Content-Type: application/json

{
    "page_size" : 2,
    "page_number" : 1
}


#########
# delete a product
DELETE http://localhost:4000/products/c9d7f85f-5b60-48fb-a04f-c55cfeb3c1ac


